language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
#    - 'pypy'  # dbm test fails, remove for now...

sudo: false

addons:
  apt:
    packages:
      - strace

install:
  - pip install .
  - pip install -r dev_requirements.txt python-coveralls

branches:
  only:
    - master
    - test


script:
   - doit pyflakes
   - py.test
   - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then doit coverage; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi

notifications:
    email:
        on_success: change
        on_failure: change
